services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vm-app
    ports:
      - "8080:8080"
    environment:
      # Database connection (these match your Go env variable keys)
      - APP_PORT=8080
      - IMAGE_MANAGER_SERVICE_NAME=image-manager:8081
      - INFRA_MONITOR_SERVICE_NAME=infra-monitor:8082
      - VM_MONITOR_SERVICE_NAME=vm-monitor:8083
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=test@123
      - DB_NAME=vmdb
      - DB_MAX_IDLE=10
      - DB_MAX_OPEN=100
      - DB_CONN_LIFETIME=60
      - CLIENT_URL=http://app:8080
      - VALIDATE_CLIENT_REQUEST=false
    depends_on:
      db:
        condition: service_healthy
    restart: always
    # Optional: If your Go binary or logs need persistent data
    # volumes:
    #   - ./logs:/app/logs
    networks:
      - vm-network

  db:
    image: mysql:8.0
    container_name: vm-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test@123
      MYSQL_DATABASE: vmdb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
    # volumes:
    #   - db_data:/var/lib/mysql
    networks:
      - vm-network
# volumes:
#   db_data:
networks:
  vm-network:
    driver: bridge
