// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	modals "vm/internal/modals"

	mock "github.com/stretchr/testify/mock"
)

// VMRepository is an autogenerated mock type for the VMRepository type
type VMRepository struct {
	mock.Mock
}

// CreateVMDeployInstances provides a mock function with given fields: ctx, requestID, baseVMName, count
func (_m *VMRepository) CreateVMDeployInstances(ctx context.Context, requestID string, baseVMName string, count int) error {
	ret := _m.Called(ctx, requestID, baseVMName, count)

	if len(ret) == 0 {
		panic("no return value specified for CreateVMDeployInstances")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = rf(ctx, requestID, baseVMName, count)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateVMRequest provides a mock function with given fields: ctx, req
func (_m *VMRepository) CreateVMRequest(ctx context.Context, req *modals.VMRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateVMRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *modals.VMRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllVMRequestsWithInstances provides a mock function with given fields: ctx
func (_m *VMRepository) GetAllVMRequestsWithInstances(ctx context.Context) ([]*modals.VMRequest, []*modals.VMDeployInstance, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllVMRequestsWithInstances")
	}

	var r0 []*modals.VMRequest
	var r1 []*modals.VMDeployInstance
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*modals.VMRequest, []*modals.VMDeployInstance, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*modals.VMRequest); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*modals.VMRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) []*modals.VMDeployInstance); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*modals.VMDeployInstance)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetVMDeployInstances provides a mock function with given fields: ctx, requestID
func (_m *VMRepository) GetVMDeployInstances(ctx context.Context, requestID string) ([]*modals.VMDeployInstance, error) {
	ret := _m.Called(ctx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for GetVMDeployInstances")
	}

	var r0 []*modals.VMDeployInstance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*modals.VMDeployInstance, error)); ok {
		return rf(ctx, requestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*modals.VMDeployInstance); ok {
		r0 = rf(ctx, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*modals.VMDeployInstance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVMRequest provides a mock function with given fields: ctx, requestID
func (_m *VMRepository) GetVMRequest(ctx context.Context, requestID string) (*modals.VMRequest, error) {
	ret := _m.Called(ctx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for GetVMRequest")
	}

	var r0 *modals.VMRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*modals.VMRequest, error)); ok {
		return rf(ctx, requestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *modals.VMRequest); ok {
		r0 = rf(ctx, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*modals.VMRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVMRepository creates a new instance of VMRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVMRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VMRepository {
	mock := &VMRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
