// Code generated by ogen, DO NOT EDIT.

package client

// GetVmMetricsParams is parameters of getVmMetrics operation.
type GetVmMetricsParams struct {
	// Unique identifier of the virtual machine.
	VMID string
}
