
openapi: 3.0.0
info:
  description: Virtualization API
  license:
    name: HPE End User License Agreement
    url: https://www.hpe.com/us/en/software/licensing.html
  title: Virtualization API
  version: 1.2.0
servers:
  - url: https://in-north.api.greenlake.hpe.com
  - url: https://in-south.api.greenlake.hpe.com
security:
  - bearer: []
tags:
  - description: >-
      The image manager API gets the Hypervisor Image
    name: image-manager
paths:
  /virtualization/v1beta1/image-manager/{image-id}:
    get:
      description: Details of an image  
      operationId: GetImage
      parameters:
        - in: path
          name: image-id
          required: true
          schema:
            description: UUID string uniquely identifying the image.
            example: 9b4c14a6-3cd5-4907-97c4-cf44c5b641e4
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'
          description: Success
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized request
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Resource not found
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal / unexpected error
      summary: Get a image resource identified by {image-id}
      tags:
        - image
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        debugId:
          description: A unique identifier for the request
          example: f57dcca3345820eb579c9317ce36dd92
          type: string
        errorCode:
          description: A machine friendly identifier for the error response
          type: string
        httpStatusCode:
          description: The HTTP status code of the response
          type: integer
        message:
          description: A user-friendly error message
          example: An example error message
          type: string
      required:
        - httpStatusCode
        - message
        - errorCode
        - debugId
    Image:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
          description: Unique identifier for the image.
          example: "img_12345"
          minLength: 1
        name:
          type: string
          description: Name of the image file or resource.
          example: "profile_picture"
          minLength: 1
        type:
          type: string
          description: Image type or format (e.g., png, jpeg).
          example: "png"
          minLength: 1
      required:
        - id
        - name
        - type
  securitySchemes:
    bearer:
      bearerFormat: JWT
      description: >
        The Data Service Cloud Console API uses a JWT bearer token for
        authentication.
 
        An authentication token can be obtained from the HPE GreenLake console.
      scheme: bearer
      type: http
