// Code generated by ogen, DO NOT EDIT.

package api

// DatastoreParams is parameters of Datastore operation.
type DatastoreParams struct {
	DatastoreID string
}

// GetImageParams is parameters of GetImage operation.
type GetImageParams struct {
	ImageID string
}

// GetVmParams is parameters of GetVm operation.
type GetVmParams struct {
	VMID string
}

// HypervisorClusterParams is parameters of HypervisorCluster operation.
type HypervisorClusterParams struct {
	ClusterID string
}

// HypervisorHostParams is parameters of HypervisorHost operation.
type HypervisorHostParams struct {
	HostID string
}
