// Code generated by ogen, DO NOT EDIT.
package api

type DatastoreRes interface {
	datastoreRes()
}

type GetImageRes interface {
	getImageRes()
}

type GetVmRes interface {
	getVmRes()
}

type HypervisorClusterRes interface {
	hypervisorClusterRes()
}

type HypervisorHostRes interface {
	hypervisorHostRes()
}
