// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	DatastoreOperation         OperationName = "Datastore"
	GetImageOperation          OperationName = "GetImage"
	GetVmOperation             OperationName = "GetVm"
	HypervisorClusterOperation OperationName = "HypervisorCluster"
	HypervisorHostOperation    OperationName = "HypervisorHost"
)
