// Code generated by ogen, DO NOT EDIT.

package client

// OperationName is the ogen operation name
type OperationName = string

const (
	GetHypervisorClustersOperation OperationName = "GetHypervisorClusters"
	GetHypervisorHostsOperation    OperationName = "GetHypervisorHosts"
)
