// Code generated by ogen, DO NOT EDIT.

package client

// DatastoreParams is parameters of Datastore operation.
type DatastoreParams struct {
	DatastoreID string
}

// HypervisorClusterParams is parameters of HypervisorCluster operation.
type HypervisorClusterParams struct {
	ClusterID string
}

// HypervisorHostParams is parameters of HypervisorHost operation.
type HypervisorHostParams struct {
	HostID string
}
