// Code generated by ogen, DO NOT EDIT.

package client

import (
	"time"
)

type Bearer struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *Bearer) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *Bearer) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *Bearer) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *Bearer) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/VmMetrics
type VmMetrics struct {
	CPUCores int     `json:"cpu_cores"`
	CPUUsage float32 `json:"cpu_usage"`
	Guest    string  `json:"guest"`
	// Memory size in GB.
	MemSize float32 `json:"mem_size"`
	// Memory usage in MB.
	MemUsage       float32 `json:"mem_usage"`
	NetworkAddress string  `json:"network_address"`
	// Network usage in MB.
	NetworkUsage    float32   `json:"network_usage"`
	ObservationTime time.Time `json:"observation_time"`
	Powerstate      string    `json:"powerstate"`
	UpdatedAt       time.Time `json:"updated_at"`
	// Uptime in hours.
	Uptime     float32 `json:"uptime"`
	VMMinusID  string  `json:"vm-id"`
	VMMetadata string  `json:"vm_metadata"`
	VMName     string  `json:"vm_name"`
	VMStat     string  `json:"vm_stat"`
}

// GetCPUCores returns the value of CPUCores.
func (s *VmMetrics) GetCPUCores() int {
	return s.CPUCores
}

// GetCPUUsage returns the value of CPUUsage.
func (s *VmMetrics) GetCPUUsage() float32 {
	return s.CPUUsage
}

// GetGuest returns the value of Guest.
func (s *VmMetrics) GetGuest() string {
	return s.Guest
}

// GetMemSize returns the value of MemSize.
func (s *VmMetrics) GetMemSize() float32 {
	return s.MemSize
}

// GetMemUsage returns the value of MemUsage.
func (s *VmMetrics) GetMemUsage() float32 {
	return s.MemUsage
}

// GetNetworkAddress returns the value of NetworkAddress.
func (s *VmMetrics) GetNetworkAddress() string {
	return s.NetworkAddress
}

// GetNetworkUsage returns the value of NetworkUsage.
func (s *VmMetrics) GetNetworkUsage() float32 {
	return s.NetworkUsage
}

// GetObservationTime returns the value of ObservationTime.
func (s *VmMetrics) GetObservationTime() time.Time {
	return s.ObservationTime
}

// GetPowerstate returns the value of Powerstate.
func (s *VmMetrics) GetPowerstate() string {
	return s.Powerstate
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *VmMetrics) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// GetUptime returns the value of Uptime.
func (s *VmMetrics) GetUptime() float32 {
	return s.Uptime
}

// GetVMMinusID returns the value of VMMinusID.
func (s *VmMetrics) GetVMMinusID() string {
	return s.VMMinusID
}

// GetVMMetadata returns the value of VMMetadata.
func (s *VmMetrics) GetVMMetadata() string {
	return s.VMMetadata
}

// GetVMName returns the value of VMName.
func (s *VmMetrics) GetVMName() string {
	return s.VMName
}

// GetVMStat returns the value of VMStat.
func (s *VmMetrics) GetVMStat() string {
	return s.VMStat
}

// SetCPUCores sets the value of CPUCores.
func (s *VmMetrics) SetCPUCores(val int) {
	s.CPUCores = val
}

// SetCPUUsage sets the value of CPUUsage.
func (s *VmMetrics) SetCPUUsage(val float32) {
	s.CPUUsage = val
}

// SetGuest sets the value of Guest.
func (s *VmMetrics) SetGuest(val string) {
	s.Guest = val
}

// SetMemSize sets the value of MemSize.
func (s *VmMetrics) SetMemSize(val float32) {
	s.MemSize = val
}

// SetMemUsage sets the value of MemUsage.
func (s *VmMetrics) SetMemUsage(val float32) {
	s.MemUsage = val
}

// SetNetworkAddress sets the value of NetworkAddress.
func (s *VmMetrics) SetNetworkAddress(val string) {
	s.NetworkAddress = val
}

// SetNetworkUsage sets the value of NetworkUsage.
func (s *VmMetrics) SetNetworkUsage(val float32) {
	s.NetworkUsage = val
}

// SetObservationTime sets the value of ObservationTime.
func (s *VmMetrics) SetObservationTime(val time.Time) {
	s.ObservationTime = val
}

// SetPowerstate sets the value of Powerstate.
func (s *VmMetrics) SetPowerstate(val string) {
	s.Powerstate = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *VmMetrics) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// SetUptime sets the value of Uptime.
func (s *VmMetrics) SetUptime(val float32) {
	s.Uptime = val
}

// SetVMMinusID sets the value of VMMinusID.
func (s *VmMetrics) SetVMMinusID(val string) {
	s.VMMinusID = val
}

// SetVMMetadata sets the value of VMMetadata.
func (s *VmMetrics) SetVMMetadata(val string) {
	s.VMMetadata = val
}

// SetVMName sets the value of VMName.
func (s *VmMetrics) SetVMName(val string) {
	s.VMName = val
}

// SetVMStat sets the value of VMStat.
func (s *VmMetrics) SetVMStat(val string) {
	s.VMStat = val
}
