// Code generated by ogen, DO NOT EDIT.

package client

import (
	"net/url"
)

type Bearer struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *Bearer) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *Bearer) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *Bearer) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *Bearer) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/HypervisorImage
type HypervisorImage struct {
	// Unique identifier for the image.
	ID string `json:"id"`
	// Name of the image file.
	Filename string `json:"filename"`
	// OS distribution and version.
	Distribution string `json:"distribution"`
	// Description of the image.
	Description string `json:"description"`
	// SHA-256 checksum of the image file.
	ChecksumSHA256 string `json:"checksum_sha256"`
	// Size of the image in gigabytes.
	SizeGB float32 `json:"size_gb"`
	// Direct URL to download or access the image.
	ImageURL url.URL `json:"image_url"`
}

// GetID returns the value of ID.
func (s *HypervisorImage) GetID() string {
	return s.ID
}

// GetFilename returns the value of Filename.
func (s *HypervisorImage) GetFilename() string {
	return s.Filename
}

// GetDistribution returns the value of Distribution.
func (s *HypervisorImage) GetDistribution() string {
	return s.Distribution
}

// GetDescription returns the value of Description.
func (s *HypervisorImage) GetDescription() string {
	return s.Description
}

// GetChecksumSHA256 returns the value of ChecksumSHA256.
func (s *HypervisorImage) GetChecksumSHA256() string {
	return s.ChecksumSHA256
}

// GetSizeGB returns the value of SizeGB.
func (s *HypervisorImage) GetSizeGB() float32 {
	return s.SizeGB
}

// GetImageURL returns the value of ImageURL.
func (s *HypervisorImage) GetImageURL() url.URL {
	return s.ImageURL
}

// SetID sets the value of ID.
func (s *HypervisorImage) SetID(val string) {
	s.ID = val
}

// SetFilename sets the value of Filename.
func (s *HypervisorImage) SetFilename(val string) {
	s.Filename = val
}

// SetDistribution sets the value of Distribution.
func (s *HypervisorImage) SetDistribution(val string) {
	s.Distribution = val
}

// SetDescription sets the value of Description.
func (s *HypervisorImage) SetDescription(val string) {
	s.Description = val
}

// SetChecksumSHA256 sets the value of ChecksumSHA256.
func (s *HypervisorImage) SetChecksumSHA256(val string) {
	s.ChecksumSHA256 = val
}

// SetSizeGB sets the value of SizeGB.
func (s *HypervisorImage) SetSizeGB(val float32) {
	s.SizeGB = val
}

// SetImageURL sets the value of ImageURL.
func (s *HypervisorImage) SetImageURL(val url.URL) {
	s.ImageURL = val
}
