// Code generated by ogen, DO NOT EDIT.
package client

type DatastoreRes interface {
	datastoreRes()
}

type HypervisorClusterRes interface {
	hypervisorClusterRes()
}

type HypervisorHostRes interface {
	hypervisorHostRes()
}
