openapi: 3.0.0
info:
  title: Virtualization API
  description: Virtualization API to retrieve virtual machine metrics.
  version: 1.2.0
  license:
    name: HPE End User License Agreement
    url: https://www.hpe.com/us/en/software/licensing.html
servers:
  - url: https://ind-north.api.greenlake.hpe.com
  - url: https://ind-south.api.greenlake.hpe.com
security:
  - bearer: []
tags:
  - name: vm-metrics
    description: The VM metrics API retrieves performance and status data for virtual machines.

paths:
  /virtualization/v1beta1/virtual-machines/vm_metrics/{vm-id}:
    get:
      tags:
        - vm-metrics
      summary: Retrieve metrics for a specific virtual machine
      description: Returns performance and status metrics for the specified virtual machine.
      operationId: getVmMetrics
      parameters:
        - name: vm-id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the virtual machine.
      responses:
        '200':
          description: Metrics for the specified virtual machine
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VmMetrics'

components:
  schemas:
    VmMetrics:
      type: object
      additionalProperties: false
      properties:
        cpu_cores:
          type: integer
          example: 1
        cpu_usage:
          type: number
          format: float
          example: 75.3
        guest:
          type: string
          example: linuxGuest
        mem_size:
          type: number
          format: float
          description: Memory size in GB
          example: 16.0
        mem_usage:
          type: number
          format: float
          description: Memory usage in MB
          example: 8192.0
        network_address:
          type: string
          example: N/A
        network_usage:
          type: number
          format: float
          description: Network usage in MB
          example: 120.5
        observation_time:
          type: string
          format: date-time
          example: Tue, 28 Oct 2025 08:48:56 GMT
        powerstate:
          type: string
          example: unknown
        updated_at:
          type: string
          format: date-time
          example: Tue, 28 Oct 2025 08:48:56 GMT
        uptime:
          type: number
          format: float
          description: Uptime in hours
          example: 0.0
        vm-id:
          type: string
          example: vm-62
        vm_metadata:
          type: string
          example: N/A
        vm_name:
          type: string
          example: DC0_H0_VM0
        vm_stat:
          type: string
          example: Active
      required:
        - cpu_cores
        - cpu_usage
        - guest
        - mem_size
        - mem_usage
        - network_address
        - network_usage
        - observation_time
        - powerstate
        - updated_at
        - uptime
        - vm-id
        - vm_metadata
        - vm_name
        - vm_stat

  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: >
        The Data Service Cloud Console API uses a JWT bearer token for authentication.

        An authentication token can be obtained from the HPE GreenLake console.