// Code generated by ogen, DO NOT EDIT.

package client

type Bearer struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *Bearer) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *Bearer) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *Bearer) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *Bearer) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	// A unique identifier for the request.
	DebugId string `json:"debugId"`
	// A machine friendly identifier for the error response.
	ErrorCode string `json:"errorCode"`
	// The HTTP status code of the response.
	HttpStatusCode int `json:"httpStatusCode"`
	// A user-friendly error message.
	Message string `json:"message"`
}

// GetDebugId returns the value of DebugId.
func (s *ErrorResponse) GetDebugId() string {
	return s.DebugId
}

// GetErrorCode returns the value of ErrorCode.
func (s *ErrorResponse) GetErrorCode() string {
	return s.ErrorCode
}

// GetHttpStatusCode returns the value of HttpStatusCode.
func (s *ErrorResponse) GetHttpStatusCode() int {
	return s.HttpStatusCode
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() string {
	return s.Message
}

// SetDebugId sets the value of DebugId.
func (s *ErrorResponse) SetDebugId(val string) {
	s.DebugId = val
}

// SetErrorCode sets the value of ErrorCode.
func (s *ErrorResponse) SetErrorCode(val string) {
	s.ErrorCode = val
}

// SetHttpStatusCode sets the value of HttpStatusCode.
func (s *ErrorResponse) SetHttpStatusCode(val int) {
	s.HttpStatusCode = val
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val string) {
	s.Message = val
}

type GetImageForbidden ErrorResponse

func (*GetImageForbidden) getImageRes() {}

type GetImageInternalServerError ErrorResponse

func (*GetImageInternalServerError) getImageRes() {}

type GetImageNotFound ErrorResponse

func (*GetImageNotFound) getImageRes() {}

type GetImageUnauthorized ErrorResponse

func (*GetImageUnauthorized) getImageRes() {}

// Ref: #/components/schemas/Image
type Image struct {
	// Unique identifier for the image.
	ID string `json:"id"`
	// Name of the image file or resource.
	Name string `json:"name"`
	// Image type or format (e.g., png, jpeg).
	Type string `json:"type"`
}

// GetID returns the value of ID.
func (s *Image) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *Image) GetName() string {
	return s.Name
}

// GetType returns the value of Type.
func (s *Image) GetType() string {
	return s.Type
}

// SetID sets the value of ID.
func (s *Image) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Image) SetName(val string) {
	s.Name = val
}

// SetType sets the value of Type.
func (s *Image) SetType(val string) {
	s.Type = val
}

func (*Image) getImageRes() {}
